### ISSUE TITLE
linux_aio : ImportError: Error on io_setup with code 22

### ISSUE THREAD

**Issue by zepedaj** [mosquito/caio#19]
## Long story short

Trying to run the CAIO_IMPL=linux version unsuccessfully. I see the required 'linux_aio' and  'linux_aio_asynio' are present, along with 'inux_aio.cpython-38-x86_64-linux-gnu.so'. Trying to import 'linux_aio' produces this error:

ImportError: Error on io_setup with code 22

## Expected behavior

Expected the linux version to work

## Actual behavior

I get the erro message above. 

## Environment info

Linux deepdell 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
File system: ext4

I have been produced this problem with implementations:

 * [] `export CAIO_IMPL=linux` - Native linux implementation

## Additional info

Ubuntu 20.04 LTS. I've tried installing the packages libaio1, libaio-dev, build-essential, same error.

**Comment by mosquito** [comment]
Could you please check my fix by running a chort c example:

```c
// write following lines to io_setup-test.c
#include <errno.h>
#include <linux/aio_abi.h>
#include <stdio.h>
#include <string.h>
#include <sys/syscall.h>

static  int io_setup(unsigned nr, aio_context_t *ctxp) {
    return syscall(__NR_io_setup, nr, ctxp);
}

int main(int argc, char *argv[]) {
    aio_context_t ctx = 0;
   
    if (io_setup(255, &ctx) != 0) {
	printf("Error [%d]: %s\n", errno, strerror(errno));
	return 1;
    }
 
    printf("Success\n");
    return 0;

}
```

After that run ``gcc io_setup-test.c && ./a.out``

**Comment by zepedaj** [comment]
Importing the module works now, and all tests pass.  

The `io_setup-test.c` example you pasted above above seems to work (*Success* printed at the end). Here is the full output:


```
bash:~/tmp$ gcc io_setup-test.c && ./a.out
io_setup-test.c: In function ‘io_setup’:
io_setup-test.c:9:12: warning: implicit declaration of function ‘syscall’ [-Wimplicit-function-declaration]
    9 |     return syscall(__NR_io_setup, nr, ctxp);
      |            ^~~~~~~
Success
```

**Comment by mosquito** [comment]
Ok could you please check a new version?
